### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by ShahramNo** [dotnetzoom/AspNetCore-WebApi-Course#106]
سلام . 
در صفحه سواگر با زدن دکمه 
Authorize
و پر کردن فیلد ها این مقادیر به سمت کنترلر فرستاده نمیشود.  و  سوال دوم در مودال لاگین مقدار 
grant_type  
را  نمیتوان وارد نمود. با تشکر

**Comment by mjebrahimi** [comment]
سلام
ممنون بابت گزارش  

چون ادرس port به صورت هارد کد نوشته شده بود. روی Kestrel (پورت 5001) اوکی بود ولی روی IIS Express خیر [که این مورد اصلاح شد.](https://github.com/dotnetzoom/AspNetCore-WebApi-Course/commit/80b78beccddf75636fbdea40b057e4404654de43#diff-04b7fe07540f95c0feef71762d4427e2L130)

در مورد grat_type امکان ارسال مقدار به اکشن Token وجود داره ولی باتوجه به اینکه مقدار grant_type برای دریافت توکن باید برابر password باشه، [هرچیزی غیر از این رو خطا صادر میکنیم.](https://github.com/dotnetzoom/AspNetCore-WebApi-Course/blob/80b78beccddf75636fbdea40b057e4404654de43/MyApi/Controllers/v1/UsersController.cs#L83)
