### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by ShahramNo** [dotnetzoom/AspNetCore-WebApi-Course#107]
با سلام خدمت شما
مودل یوزر نمیتونه از 
ientity
ارث بری کنه . چون یوزر از 
identity 
ارث بری کرده و 
Id 
دارد. برای همین اگر بخواهیم یوزر را به سایر جداول ریلیشن بزنیم در هنگام عملیات کراد ممکن از با خطا مواجه شود.

**Comment by mjebrahimi** [comment]
سلام
متوجشه منظوتون نشدم
IEntity یک interface  هست که در نوع جنریک اون نوع آیدی TKey رو هم میشه مشخص کرد.
چرا کلاس User نمیتونه از اون ارث بری کنه؟ 
در [اینجا](https://github.com/dotnetzoom/AspNetCore-WebApi-Course/blob/80b78beccddf75636fbdea40b057e4404654de43/Entities/User/User.cs#L10) هم ما ارث بری کردیم
```csharp
public class User : IdentityUser<int>, IEntity
```

**Comment by ShahramNo** [comment]
درسته حق با شماست . من توی پروژه خودم ارور داشتم .ولی اینجا درسته .ممنون از پاسختان
