### ISSUE TITLE
Refresh Token and Pagination

### ISSUE THREAD

**Issue by nddashti** [dotnetzoom/AspNetCore-WebApi-Course#108]
سلام
لذت بردم از کدتون لطفا در صورت امکان refresh token و همچنین pagination dynamic را هم داخل پروژه تون پیاده سازی کنید.
ممنون

**Comment by mjebrahimi** [comment]
سلام 

بدلیل اینکه این سورس برای یک دوره آموزشی تهیه شده است، متاسفانه افزودن قابلیت های خارج از اون دوره امکانش نیست
