### ISSUE TITLE
Current User

### ISSUE THREAD

**Issue by ShahramNo** [dotnetzoom/AspNetCore-WebApi-Course#109]
با سلام . اگر بخواهیم در جدول هایی که به یوزر وصل هستند ای دی یوزر فعلی را قرار بدهیم از طریق همین جنریک ریپازیتوری . اگر امکانش هست توضیح دهید.
مثلا ایدی کسی که ویرایش یا جدید انجام داده در جدول مربوطه ذخیره کنیم.

**Comment by mjebrahimi** [comment]
سلام

موارد رفع اشکال و آموزش بیشتر در این مخزن ترتیب اثر داده نمیشوند.
