### ISSUE TITLE
Speed

### ISSUE THREAD

**Issue by ShahramNo** [dotnetzoom/AspNetCore-WebApi-Course#110]
استاد این فریم ورد جهت پروژه های بزرگ قابل استفاده است؟ به لحاظ سرعت . چون به علت جنریک بود ککنترل ها و سایر سرویس ها اینها باید در هر لحظه با توجه ده درخواست ایجاد شوند. که ممکن است باعت کندی سرعت شوند. ؟

**Comment by mjebrahimi** [comment]
استفاده از جنریک باعث کاهش سرعت نمیشه (در بعضی موارد خاص اگرهم تاثیری داشته باشه micro optimization محسوب میشه و برای پروژه های بیزینسی چه بزرگ و چه کوچک به حساب نمیاد) پس به هیچ عنوان نگران این موضوع نباشید. مخصوصا وقتی شما یک پروژه بیزینسی دارید، سطح دغدغه های پرفرمنسی کاملا متفاوت هستند (مانند بهنیه سازی لایه ارتباط با دیتابیس، کوئری ها، کش کردن، استفاده از async به جای sync و...)
