### ISSUE TITLE
Dto in ServiceLayer

### ISSUE THREAD

**Issue by ShahramNo** [dotnetzoom/AspNetCore-WebApi-Course#123]
سلام . تشکر از اموزش خوبتون. چرا ما نمیتونیم توی لایه سرویس از ویومدل هایی که در لایه api ساختیم استفاده کنیم؟
مگر لایه سرویس نمیتونه ویو مدل بگیره؟

**Comment by mjebrahimi** [comment]
سلام
اصولا ViewModel مربوطه به لایه Presentation (در اینجا وب ما) هست واستفاده ازش تو لایه Service درست نیست
ولی اگر از DTO ها در لایه سرویس استفاده کنیم اشکالی نداره
DTO و ViewModel خیلی شبیه به هم هستند ولی تفاوتشون در اینه که DTO یک کلاس (بدون متد/رفتار) برای انتقال دیتا هست در حالی که ViewModel میتونه رفتار (متد) هایی  یا دیتا های دیگری که برای لایه Presentation لازم هستند رو هم داشته باشه
مثلا یک ViewModel میتونه دارای فیلدی از نوع `SelectList `(یا `IEnumerable<SelectListItem>`) باشه که دیتای لازم برای نمایش در DropDown در Mvc Razor رو داره
یا مثلا میتونه متدی برای Render کردن ViewModel در حالتی خاص برای لایه Presentation داشته باشه
و این میتونه توی الگوی MVVM متفاوت هم باشه
پس در کل ViewModel میتونه دارای فیلد ها و متد هایی فراتر از DTO باشه که صرفا در لایه Presentation کاربرد دارند به همین دلیل استفاده از اون تو لایه سرویس صحیح نیست که در غیر اینصورت لایه سرویس ما وابسته به لایه Presentation میشه که اشتباه هست
شما باید به این دید نگاه کنید که اگر لازم شد لایه Presentation رو عوض کنید، هیچ تغییری در لایه سرویس نیاز نباشه
