### ISSUE TITLE
Overrid crud

### ISSUE THREAD

**Issue by ShahramNo** [dotnetzoom/AspNetCore-WebApi-Course#126]
سلام و خسته نباشید. 
یک سوال داشتم در مورد اینکه اگر در کنترلر های جنریک که از  CrudController ارث بری کرده اند 
یک متد را اوراید کنیم. و مثلا یک crate جدید بنویسیم
اما مابقی متد ها تغیر نکنند چه کار باید انجام داد؟
با تشکر از اموزش خوبتون

**Comment by mjebrahimi** [comment]
از لحاظ فنی ایرادی نداره اگه بقیه رو override نکنیم و حتی درست تر هم هست و عملا خود ASP Core بدرستی با این موضوع کار میکنه

ولی این یک باگ Swagger هست که حتما باید بقیه رو هم override کنیم وگرنه خطا میده و نمیتونه اکشن های ارث بری شده رو شناسایی کنه
