### ISSUE TITLE
Add OData

### ISSUE THREAD

**Issue by EliasTaghavi** [dotnetzoom/AspNetCore-WebApi-Course#162]
Add OData functionality to project, which is useful for querying data

**Comment by mjebrahimi** [comment]
سلام دوست عزیز

این پروژه چون برای یک دوره مشخص ضبط شده نمخوام سورسش تغییر کنه؛ مگر رفع باگ یا بروزرسانی به ورژن های جدید تر پکیج ها

شاید ایده بهتری باشه که یه پروژه دیگه ایجاد بشه که هم امکانات بیشتری داشته باشه از جمله همین OData و هم Best Practice ها واصول بیشتری توش وجود داشته باشه

احتمالا همین کار رو بکنم ولی فعلا فرصتش رو ندارم؛ انشالا به در آینده ای نه چندان دور
