### ISSUE TITLE
Architecture does not fully support the unit tests

### ISSUE THREAD

**Issue by nazarireza** [dotnetzoom/AspNetCore-WebApi-Course#2]
The architecture does not fully support the unit tests. You should use other architectures like Onion, CQRS or DDD for full coverage of the unit tests. N-Tier usually is used for CRUD projects.

**Comment by mjebrahimi** [comment]
The architecture of this project is not N-Tier!
This is **Onion architecture** with little customization and improvement. please read carefully "[Onion Architecture In ASP.NET Core MVC](https://www.c-sharpcorner.com/article/onion-architecture-in-asp-net-core-mvc/)"

Generally, the main purpose of DDD is to simplify the complexity of business logic (not testability ) and should be considered according to the project conditions, NOT Everywhere.
This Course (of the project) is **Web API best practices and techniques** and it's not about DDD or CQRS.
Therefore, to avoid unnecessary complexity, these subjects have been ignored.

Also, **CQRS is not an architecture**, it is a pattern and Its benefits is independent scaling, independent read and write optimization and separation of concerns... and **Testability is not one of the benefits of this method**. (check out [microsoft article](https://docs.microsoft.com/en-us/azure/architecture/patterns/cqrs) and [martin fowler article](https://martinfowler.com/bliki/CQRS.html))

In the end, if you could just give an example, that writing test would not be possible in this project :)
