### ISSUE TITLE
The corresponding CLR type for entity type 'Post' is not instantiable and there is no derived entity type in the model that corresponds to a concrete CLR type.

### ISSUE THREAD

**Issue by Shmata** [dotnetzoom/AspNetCore-WebApi-Course#3]
Dear @mjebrahimi  , 
When I execute 
> Add-Migration initial 

I encounter with below error, 
Can you tell me how to solve it ? 
![issuepng](https://user-images.githubusercontent.com/2398297/62756309-7dc8a500-ba8c-11e9-8a5a-d5ef76e188b9.png)

**Comment by Shmata** [comment]
That was my fault, the problem was Post class became abstract so I removed abstract keyword then Migration generated successfully

**Comment by GorginMajid** [comment]
Thats Right,I Remove **abstract** it`s Worked
