### ISSUE TITLE
اشتراک گذاری منبع

### ISSUE THREAD

**Issue by Gitareschoob** [dotnetzoom/AspNetCore-WebApi-Course#374]
سلام عرض خسته نباشید من یه فریم ورک ایرانی دیدم که واقعا توی فریم ورک ها  خیلی تمیز بود مثلا برای عملیات کراد دیگه نیاز نبود بهش بگی مپ را 
 انجام بده و خودش توی لایه ریپوزیتوری این کار را انجام میداد و یه سری قابلیت دیگه گفتم یاهاتون به اشتراک بذارم تاشاید به درد بخوره و ماهایی که علممون کلمتره بتونیم توی اپدیت پکیج هاتون این هارا یاد بگیریم
https://auaframework.com/Website/DownloadBasicPackage

**Comment by mjebrahimi** [comment]
مرسی بابت اشتراک گذاری، این سورس چون مربوط به یه دوره از قبل تدریس شده هست نمیخوام تغییر فانکشنالی روی سورس بدم و فقط بروزرسانی ها رو روش اعمال میکنم
