### ISSUE TITLE
ProjectTo

### ISSUE THREAD

**Issue by Gitareschoob** [dotnetzoom/AspNetCore-WebApi-Course#377]
سلام توی تغییرات جدید 
.ProjectTo<GetUserFromLoginDto>(mapper.ConfigurationProvider)

این کار نمیکنه و ارور 
InvalidOperationException: Missing map from Entities.User.User to Core.DTO.GetUserFromLoginDto. Create using CreateMap<User, GetUserFromLoginDto>.
را میده  در صورتی که بقیه قسمت ها داره درست کار میکتنه چجوری میشه درستش کنم؟

public class GetUserFromLoginDto
    {
        public long Id { get; set; }
        public string FullName { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public string RoleTitle { get; set; }
        public string RoleName { get; set; }
        public bool IsActive { get; set; }
    }

**Comment by mjebrahimi** [comment]
این خطا میگه mapping نوع User به نوع GetUserFromLoginDto تعریف نشده. یا باید خودت دستی تعریفش کنی مثل زیر

```c#
public class UserMappingProfile : Profile
{
    public WebMappingProfile()
    {
        CreateMap<User, GetUserFromLoginDto>();
    }
}
```

یا که کافیه از `BaseDto<GetUserFromLoginDto, User, long>` ارث بری کنی تا خودکار مپینگش تعریف بشه و فیلد Id هم دیگه لازم نداری  
```c#
public class GetUserFromLoginDto : BaseDto<GetUserFromLoginDto, User, long>
{
   public string FullName { get; set; }
   public string PhoneNumber { get; set; }
   public string Email { get; set; }
   public string RoleTitle { get; set; }
   public string RoleName { get; set; }
   public bool IsActive { get; set; }
}
```
