### ISSUE TITLE
why when add new Entity  create BaseEntity<Guid>s in databse

### ISSUE THREAD

**Issue by sajadghobadi** [dotnetzoom/AspNetCore-WebApi-Course#378]
thanks for your template.
when i create new entity(for example city) inherited from BaseEntity<Guid> and run project, migration applied.
but i see one table with BaseEntity<Guid>s created.
where is my mistak?
![Capture](https://user-images.githubusercontent.com/7240130/152418621-7fef9ef4-3c66-46e7-a1cf-436fbed31618.PNG)

**Comment by mjebrahimi** [comment]
You're welcome.
Wow, this is something completely new and strange! I had never seen such a thing before.
Can you send me the code that caused this output?

**Comment by sajadghobadi** [comment]
in master branch you can add new entity to Entities project with inherited from BaseEntity<Guid> like this :
```
 public class Group:BaseEntity<Guid>
    {
        public string Name { get; set; }

        public string PathologicalDescription { get; set; }     
    }
```
but after run MyAPI project that normally run  IntializeDatabase method, you can see database not created table with Groups name.
you can test now with current code in Master branch

**Comment by mjebrahimi** [comment]
This is exactly the output of that code in the master branch.

![](https://user-images.githubusercontent.com/23256135/152639611-adccf2fd-e714-4c42-906f-6e1e050275ad.png)

My suggestion is to provide a reproducible code about this problem in a repository that I can test on it.
