### ISSUE TITLE
استفاده از لایه سرویس

### ISSUE THREAD

**Issue by omidsoft** [dotnetzoom/AspNetCore-WebApi-Course#48]
سلام
من آموزش شما رو تهیه کردم و ازتون بابت این آموزش خوب و کارآمد تشکر میکنم

سوالی که داشتم اینکه در آموزش درخصوص لایه سرویس و معماری استفاده از اون صحبتی نشده

آیا دیگه نیازی به لایه سرویس نیست؟ و باید کدها رو داخل کنترلرها نوشت؟>

**Comment by mjebrahimi** [comment]
سلام ممنون

توی پروژه جاری هم قسمتی در مورد سرویس ها صحبت شده و درستش هم اینه که بیزینس لاجیک رو مستقیما توی لایه Presentation (در اینجا لایه WebApi) ننوسیم. به جاش اون ها رو داخل سرویس ها بنویسیم و اون سرویس ها رو توی کنترلر هامون (توسط تزریق وابستگی دریافت و) متد هاشو فراخوانی کنیم.

این کار باعث میشه اولا پروژه ما به لایه Presentation وابسته نشه. دوما پیچیدگی پیاده سازی ها رو داخل متد های سرویس مخفی بشه تا کنترلر هامون الکی شلوغ نشه.
