### ISSUE TITLE
خطا در ModelBuilderExtensions - 'immutable entity type' does not contain a definition for 'relational' 

### ISSUE THREAD

**Issue by Shmata** [dotnetzoom/AspNetCore-WebApi-Course#5]
![error](https://user-images.githubusercontent.com/2398297/73824040-b1ec0b00-480e-11ea-82a4-775a686d3e8b.jpg)
سلام در پروژه ای که در آموزش ویدئویی تون توضیح دادین ، من به مشکل خوردم . در کلاس 
**ModelBuilderExtensions**
با پیغام خطای بالا مواجه میشم که میگه باید از Relational ، Using کنم  
منم پکیج زیر را نصب کردم ( دومین آیتم در تصویر زیر ) 
![1](https://user-images.githubusercontent.com/2398297/73824043-b3b5ce80-480e-11ea-8bff-4863ec237978.jpg)
ولی باز همچنان مشکل وجود داره 
![2](https://user-images.githubusercontent.com/2398297/73824047-b57f9200-480e-11ea-9e9f-67d5401a469a.jpg)

میشه راهنمایی کنید ؟؟ 
ورژن .net core ام 2.1   هست

**Comment by mjebrahimi** [comment]
سلام
ورژن اون پکیجی که نصب کردین (همون Relational) نسخه 3.1.1 هست
توی تصویر سمت راست، عدد ورژن رو نوشته
شما باید نسخه 2.1.4 رو نصب میکردین
نسخه 3.1.1 مربوط به EF Core 3.1 هست که در در اون متد Relational() حذف شده
https://stackoverflow.com/a/59114563/12653948
```csharp
Pluralizer pluralizer = new Pluralizer();
foreach (IMutableEntityType entityType in modelBuilder.Model.GetEntityTypes())
{
    string tableName = entityType.GetTableName();
    entityType.SetTableName(pluralizer.Pluralize(tableName));
}

```

<br/>
<br/>

اگر میخواین از این پروژه با ASP Core 3.1 استفاده کنین تغییراتی لازم است که بروزرسانی این تغییرات در آخرین کامیت پروژه جاری، قبلا اعمال شده
لیست کلیه تغییرات رو میتونین در کامیت زیر مشاهده کنین
[Commit on Jan 5 : Upgrade to ASP.NET Core 3.1](https://github.com/dotnetzoom/AspNetCore-WebApi-Course/commit/512375f4768b4ed08f0e03cf58e14ac392cd1c3d)
